### ISSUE TITLE
Wezzer fails hard on incorrect zip code

### ISSUE THREAD

**Issue by nqnzp** [nqnzp/wezzer#7]
When you enter an incorrect zip code, wezzer should handle it better and politely say that the zip code is incorrect instead of failing hard

```
./wezzer.py  -z 11111
[*] Failed to get response from API
Traceback (most recent call last):
  File "./wezzer.py", line 251, in <module>
    main()
  File "./wezzer.py", line 145, in main
    epdata = get_endpoint_data(latlong_str)
  File "./wezzer.py", line 48, in get_endpoint_data
    return endpoint_data  # returns a json object
UnboundLocalError: local variable 'endpoint_data' referenced before assignment

```

**Comment by nqnzp** [comment]
Fix in dev branch
